= Deploy and Operate

== Deploy a GraphQL Data API


Deploying a GraphQL Data API requires you first to have completed the steps in xref::/aura-graphql-data-apis/prerequisites.adoc[Prerequisites]. Of particular importance is that you have:

* The ID, username and password for the AuraDB
* A file containing the type definitions

You are now ready to create the GraphQL Data API with the Aura CLI. Substitute the values in `CAPITALS` to match your setup:

[source, bash, indent=0]
----
aura-cli data-api graphql create --name YOUR-FRIENDLY-NAME --instance-id YOUR-AURA-INSTANCE-ID --instance-username YOUR-AURA-INSTANCE-USER --instance-password YOUR-AURA-INSTANCE-PASSWORD --type-definitions-file
FULL-PATH-TO-YOUR-TYPE-DEFS --await
----

[NOTE]
====
Make sure to record the API key shown in the response as it will not be displayed again. If the API key is lost, a new one can be created by following the steps to create a new API key auth provider in the xref::/aura-graphql-data-apis/authentication-providers.adoc[authentication provider] section
====

There are other items of note in the response:

* `id`: unique identifier for the GraphQL Data API
* `status`: tells you if the GraphQL Data API is ready to receive requests
* `url`: the connection address to access the Data API

To check if the GraphQL Data API is ready for requests, use the Aura CLI again, changing `YOUR-AURA-INSTANCE-ID` for the ID of your aura instance.

[source, bash, indent=0]
----
aura-cli data-api graphql list --instance-id YOUR-AURA-INSTANCE-ID
----

When the status changes to `ready`, the GraphQL Data API is available for servicing requests.

== Modifying an Existing GraphQL Data API

It is possible to change the configuration of an existing GraphQL Data API. The following properties can be modified:

* Friendly name of the GraphQL Data API
* Username and/or password for the associated Aura instance
* Type definitions

To do this, use the Aura CLI update command which requires IDs of the GraphQL Data API and it’s linked AuraDB instance. The format of this Aura CLI command is as follows:

[source, bash, indent=0]
----
aura-cli data-api graphql update YOUR-DATA-API-ID --instance-id YOUR-AURA-INSTANCE-ID <flags>
----

As the change takes a few moments to fully implement, you should check the status of the GraphQL Data API after performing this operation; if the status is `updating` then the change is still being processed. When the change is committed, the status will return to `ready`.


Additionally, it is possible to modify the authentication providers of a GraphQL Data APIs. More on what these are and how to do this xref::/aura-graphql-data-apis/authentication-providers.adoc[here].

== Deleting a GraphQL Data API

When you no longer require the GraphQL Data API then delete it by using the Aura CLI delete command. This will require the Aura instance ID and ID of the GraphQL Data API.

The format of this command is as follows:

[source, bash, indent=0]
----
aura-cli data-api graphql delete YOUR-DATA-API-ID --instance-id YOUR-AURA-INSTANCE-ID
----

[NOTE]
====
There is no additional confirmation - the GraphQL Data API will start to be deleted as soon as you press the Enter key!
====
