name: "Documentation Teardown"

on:
  pull_request_target:
    types:
      - closed

jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
      - name: Teardown documentation
        run: |
          npm install -g surge
          surge teardown neo4j-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.DOCS_SURGE_TOKEN }}
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@f61b6cf21ef2fcc468f4345cdfcc9bda741d2343 # v2.6.2
        with:
          header: docs
          message: |
            Thanks for the documentation updates.

            The preview documentation has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.DOCS_PR_COMMENT_TOKEN }}
